import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './component/Navbar'
import Footer from './component/Footer'
const NunitoFont = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Air BnB Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={NunitoFont.className } >
        <main className='px-2 lg:px-14 xl:px-20'>
        <Navbar/>
        {children}
        <Footer  />
        </main>
      </body>
    </html>
  )
}
